### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by mengchaoheng** [mkb9559/Distributed-Variation#1]
You have done a very beautiful job, I am very interested in your work, but I don't know how to run the code, especially the code running process, it seems that multiple files have sequential dependencies. Can you write a usage?

**Comment by mkb9559** [comment]
Thank you for your interest. Its use is very simple:

Step 1: Run init6CBF3D. m

Step 2: Run DoubleAdaptiveCBF3D.slx



You can run results. m, ender.m or showtime2D.m to view the results.
